#define ID_OPEN                         10
#define IDC_WETMIX                      100
#define IDC_DRYMIX                      101
#define IDC_ROOMSIZE                    102
#define IDC_DAMP	                    103
#define IDC_WIDTH	                    104
#define IDC_CHKMODE	                    105
#define IDC_CHKFRB                      106
#define IDC_CHKCHAN1					1
#define IDC_CHKCHAN2					2
#define IDC_CHKCHAN3					4
#define IDC_CHKCHAN4					8
#define IDC_CHKCHAN5					16
#define IDC_CHKCHAN6					32
#define IDC_CHKCHAN7					64
#define IDC_CHKCHAN8					128
#define IDC_STATIC						-1
