namespace TagsLib_API
{

  public enum TConfigFlags
  {
    TAGSLIBRARY_PADDING_SIZE_TO_WRITE = 1,
    TAGSLIBRARY_PARSE_OGG_PLAYTIME = 2,
    TAGSLIBRARY_PARSE_ID3v2_AUDIO_ATTRIBUTES = 3,
    TAGSLIBRARY_MP4TAG_KEEP_PADDING = 4,
    TAGSLIBRARY_PARSE_WAVPACK_AUDIO_ATTRIBUTES = 5,
    TAGSLIBRARY_PARSE_MUSEPACK_AUDIO_ATTRIBUTES = 6,
    TAGSLIBRARY_DEEP_OPUS_BITRATE_SCAN = 7  
  }

}