namespace TagsLib_API
{

  public enum TTagError
  {
    TAGSLIBRARY_SUCCESS = 0,
    TAGSLIBRARY_ERROR = 0xffff,
    TAGSLIBRARY_ERROR_NO_TAG_FOUND = 1,
    TAGSLIBRARY_ERROR_FILENOTFOUND = 2,
    TAGSLIBRARY_ERROR_EMPTY_TAG = 3,
    TAGSLIBRARY_ERROR_EMPTY_FRAMES = 4,
    TAGSLIBRARY_ERROR_OPENING_FILE = 5,
    TAGSLIBRARY_ERROR_READING_FILE = 6,
    TAGSLIBRARY_ERROR_WRITING_FILE = 7,
    TAGSLIBRARY_ERROR_CORRUPT = 8,
    TAGSLIBRARY_ERROR_NOT_SUPPORTED_VERSION = 9,
    TAGSLIBRARY_ERROR_NOT_SUPPORTED_FORMAT = 10,
    TAGSLIBRARY_ERROR_BASS_NOT_LOADED = 11,
    TAGSLIBRARY_ERROR_BASS_ChannelGetTags_NOT_FOUND = 12,
    TAGSLIBRARY_ERROR_DOESNT_FIT = 13,
    TAGSLIBRARY_ERROR_NEED_EXCLUSIVE_ACCESS = 14,
    TAGSLIBRARY_ERROR_WMATAGLIBRARY_COULDNTLOADDLL = 15,
    TAGSLIBRARY_ERROR_WMATAGLIBRARY_COULDNOTCREATEMETADATAEDITOR = 16,
    TAGSLIBRARY_ERROR_WMATAGLIBRARY_COULDNOTQIFORIWMHEADERINFO3 = 17,
    TAGSLIBRARY_ERROR_WMATAGLIBRARY_COULDNOTQUERY_ATTRIBUTE_COUNT = 18,
    TAGSLIBRARY_ERROR_MP4TAGLIBRARY_UPDATE_stco = 19,
    TAGSLIBRARY_ERROR_MP4TAGLIBRARY_UPDATE_co64 = 20,
    TAGSLIBRARY_ERROR_NOT_ENOUGH_MEMORY_OR_AV = 21
  }

}
